# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guiyt2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(741, 562)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../Downloads/download-da-nuvem.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_frame = QtWidgets.QFrame(self.centralwidget)
        self.button_frame.setGeometry(QtCore.QRect(10, 430, 721, 91))
        self.button_frame.setAutoFillBackground(False)
        self.button_frame.setStyleSheet("background-color: rgb(0, 170, 127);\n"
"border-radius: 10px;\n"
"\n"
"")
        self.button_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.button_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.button_frame.setObjectName("button_frame")
        self.button_frame_2 = QtWidgets.QFrame(self.button_frame)
        self.button_frame_2.setGeometry(QtCore.QRect(0, 0, 711, 81))
        self.button_frame_2.setAutoFillBackground(False)
        self.button_frame_2.setStyleSheet("background-color: rgb(0, 170, 127);\n"
"border-radius: 10px;\n"
"\n"
"")
        self.button_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.button_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.button_frame_2.setObjectName("button_frame_2")
        self.button_play = QtWidgets.QPushButton(self.button_frame_2)
        self.button_play.setGeometry(QtCore.QRect(300, 60, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_play.setFont(font)
        self.button_play.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.button_play.setProperty("play_click_event", True)
        self.button_play.setObjectName("button_play")
        self.button_anterior = QtWidgets.QPushButton(self.button_frame_2)
        self.button_anterior.setGeometry(QtCore.QRect(40, 60, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_anterior.setFont(font)
        self.button_anterior.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.button_anterior.setProperty("anterior_click_event", True)
        self.button_anterior.setObjectName("button_anterior")
        self.button_proxima = QtWidgets.QPushButton(self.button_frame_2)
        self.button_proxima.setGeometry(QtCore.QRect(590, 60, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_proxima.setFont(font)
        self.button_proxima.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.button_proxima.setProperty("proxima_click_event", False)
        self.button_proxima.setObjectName("button_proxima")
        self.button_parar = QtWidgets.QPushButton(self.button_frame_2)
        self.button_parar.setGeometry(QtCore.QRect(380, 60, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_parar.setFont(font)
        self.button_parar.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.button_parar.setProperty("parar_click_event", True)
        self.button_parar.setObjectName("button_parar")
        self.button_pause = QtWidgets.QPushButton(self.button_frame_2)
        self.button_pause.setGeometry(QtCore.QRect(220, 60, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_pause.setFont(font)
        self.button_pause.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.button_pause.setProperty("pause_click_event", True)
        self.button_pause.setObjectName("button_pause")
        self.music_pgbar = QtWidgets.QProgressBar(self.button_frame_2)
        self.music_pgbar.setGeometry(QtCore.QRect(20, 40, 671, 16))
        self.music_pgbar.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"border-radius: 10px;\n"
"")
        self.music_pgbar.setProperty("value", 0)
        self.music_pgbar.setObjectName("music_pgbar")
        self.music_tittle = QtWidgets.QLabel(self.button_frame_2)
        self.music_tittle.setGeometry(QtCore.QRect(20, 10, 671, 20))
        self.music_tittle.setStyleSheet("background: rgb(170, 255, 204)")
        self.music_tittle.setText("")
        self.music_tittle.setObjectName("music_tittle")
        self.main_frame = QtWidgets.QFrame(self.centralwidget)
        self.main_frame.setGeometry(QtCore.QRect(10, 10, 721, 421))
        self.main_frame.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(0, 0, 0);")
        self.main_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.tab_main = QtWidgets.QTabWidget(self.main_frame)
        self.tab_main.setGeometry(QtCore.QRect(0, 0, 721, 351))
        self.tab_main.setStyleSheet("\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);\n"
"")
        self.tab_main.setObjectName("tab_main")
        self.ds_tab = QtWidgets.QWidget()
        self.ds_tab.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.ds_tab.setObjectName("ds_tab")
        self.busca_scroll_area = QtWidgets.QScrollArea(self.ds_tab)
        self.busca_scroll_area.setGeometry(QtCore.QRect(10, 40, 421, 321))
        self.busca_scroll_area.setStyleSheet("background-color: rgb(49, 34, 255);\n"
"border-radius: 12px;")
        self.busca_scroll_area.setWidgetResizable(True)
        self.busca_scroll_area.setObjectName("busca_scroll_area")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 421, 321))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.busca_scroll_area.setWidget(self.scrollAreaWidgetContents)
        self.down_scroll_area = QtWidgets.QScrollArea(self.ds_tab)
        self.down_scroll_area.setGeometry(QtCore.QRect(440, 40, 271, 321))
        self.down_scroll_area.setStyleSheet("background-color: rgb(49, 34, 255);\n"
"border-radius: 12px;")
        self.down_scroll_area.setWidgetResizable(True)
        self.down_scroll_area.setObjectName("down_scroll_area")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 271, 321))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.down_scroll_area.setWidget(self.scrollAreaWidgetContents_2)
        self.lineEdit = QtWidgets.QLineEdit(self.ds_tab)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 361, 20))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 10px;")
        self.lineEdit.setProperty("busca_clickfocus_event", True)
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.ds_tab)
        self.label.setGeometry(QtCore.QRect(440, 10, 151, 16))
        font = QtGui.QFont()
        font.setFamily("Source Serif Pro")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 0, 0);")
        self.label.setObjectName("label")
        self.tab_main.addTab(self.ds_tab, "")
        self.tab_rep = QtWidgets.QWidget()
        self.tab_rep.setStyleSheet("background-color: rgb(85, 85, 255);")
        self.tab_rep.setObjectName("tab_rep")
        self.lista_music_frame = QtWidgets.QFrame(self.tab_rep)
        self.lista_music_frame.setGeometry(QtCore.QRect(489, 30, 221, 281))
        self.lista_music_frame.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.lista_music_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.lista_music_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lista_music_frame.setObjectName("lista_music_frame")
        self.tab_main.addTab(self.tab_rep, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 741, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tab_main.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Youtube Downloader"))
        self.button_play.setText(_translate("MainWindow", "Play"))
        self.button_anterior.setText(_translate("MainWindow", "Anterior"))
        self.button_proxima.setText(_translate("MainWindow", "Proxima"))
        self.button_parar.setText(_translate("MainWindow", "Parar"))
        self.button_pause.setText(_translate("MainWindow", "Pause"))
        self.lineEdit.setText(_translate("MainWindow", "Buscar"))
        self.label.setText(_translate("MainWindow", "Downloads"))
        self.tab_main.setTabText(self.tab_main.indexOf(self.ds_tab), _translate("MainWindow", "D.S"))
        self.tab_main.setTabText(self.tab_main.indexOf(self.tab_rep), _translate("MainWindow", "Listen and View"))
