# ========================================================================== #

from PyQt5.QtWidgets import QMainWindow, QWidget, QFrame
from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_MainWindow(QMainWindow):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(741, 562)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../Downloads/download-da-nuvem.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.button_frame = QtWidgets.QFrame(self.centralwidget)
        self.button_frame.setGeometry(QtCore.QRect(10, 440, 721, 81))
        self.button_frame.setAutoFillBackground(False)
        self.button_frame.setStyleSheet("background-color: rgb(0, 170, 127);\n"
                                         "border-radius: 10px;\n"
                                         "")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.button_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.button_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.button_frame.setObjectName("button_frame")
        self.button_frame_2 = QtWidgets.QFrame(self.button_frame)
        self.button_frame_2.setGeometry(QtCore.QRect(0, 0, 711, 81))
        self.button_frame_2.setAutoFillBackground(False)
        self.button_frame_2.setStyleSheet("background-color: rgb(0, 170, 127);\n"
"border-radius: 10px;\n"
"\n"
"")
        self.button_frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.button_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.button_frame_2.setObjectName("button_frame_2")
        self.button_play = QtWidgets.QPushButton(self.button_frame_2)
        self.button_play.setGeometry(QtCore.QRect(300, 50, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_play.setFont(font)
        self.button_play.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.button_play.setObjectName("button_play")
        self.button_anterior = QtWidgets.QPushButton(self.button_frame_2)
        self.button_anterior.setGeometry(QtCore.QRect(40, 50, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_anterior.setFont(font)
        self.button_anterior.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.button_anterior.setObjectName("button_anterior")
        self.button_proxima = QtWidgets.QPushButton(self.button_frame_2)
        self.button_proxima.setGeometry(QtCore.QRect(590, 50, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_proxima.setFont(font)
        self.button_proxima.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.button_proxima.setObjectName("button_proxima")
        self.button_parar = QtWidgets.QPushButton(self.button_frame_2)
        self.button_parar.setGeometry(QtCore.QRect(380, 50, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_parar.setFont(font)
        self.button_parar.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.button_parar.setObjectName("button_parar")
        self.button_pause = QtWidgets.QPushButton(self.button_frame_2)
        self.button_pause.setGeometry(QtCore.QRect(220, 50, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.button_pause.setFont(font)
        self.button_pause.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.button_pause.setObjectName("button_pause")
        self.music_pgbar = QtWidgets.QProgressBar(self.button_frame_2)
        self.music_pgbar.setGeometry(QtCore.QRect(40, 30, 631, 15))
        self.music_pgbar.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"border-radius: 10px;\n"
"")
        self.music_pgbar.setProperty("value", 0)
        self.music_pgbar.setObjectName("music_pgbar")
        self.music_tittle = QtWidgets.QLabel(self.button_frame_2)
        self.music_tittle.setGeometry(QtCore.QRect(40, 10, 471, 16))
        self.music_tittle.setText("")
        self.music_tittle.setObjectName("music_tittle")
        self.tab_main = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_main.setGeometry(QtCore.QRect(10, 10, 721, 421))
        self.tab_main.setStyleSheet("background-color: rgb(0,0,0);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.tab_main.setObjectName("tab_main")
        self.ds_tab = QtWidgets.QWidget()
        self.ds_tab.setObjectName("ds_tab")
        self.mainFrame = QtWidgets.QFrame(self.ds_tab)
        self.mainFrame.setGeometry(QtCore.QRect(0, 0, 751, 401))
        self.mainFrame.setStyleSheet("background-color: rgb(85, 170, 127)")
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.table_buscar = QtWidgets.QTableView(self.mainFrame)
        self.table_buscar.setGeometry(QtCore.QRect(10, 60, 341, 301))
        self.table_buscar.setStyleSheet("background-color: rgb(133, 180, 255);\n"
"")
        self.table_buscar.setObjectName("table_buscar")
        self.scroll_downloads = QtWidgets.QScrollArea(self.mainFrame)
        self.scroll_downloads.setGeometry(QtCore.QRect(370, 60, 321, 301))
        self.scroll_downloads.setStyleSheet("background-color: rgb(133, 180, 255);\n"
"")
        self.scroll_downloads.setWidgetResizable(True)
        self.scroll_downloads.setObjectName("scroll_downloads")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 319, 299))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.table_downloads = QtWidgets.QTableView(self.scrollAreaWidgetContents)
        self.table_downloads.setGeometry(QtCore.QRect(10, 10, 301, 271))
        self.table_downloads.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.table_downloads.setObjectName("table_downloads")
        self.scroll_downloads.setWidget(self.scrollAreaWidgetContents)
        self.lbl_bucar = QtWidgets.QLabel(self.mainFrame)
        self.lbl_bucar.setGeometry(QtCore.QRect(10, 20, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_bucar.setFont(font)
        self.lbl_bucar.setStyleSheet("color: rgb(0, 0, 0);")
        self.lbl_bucar.setObjectName("lbl_bucar")
        self.buscar_edit = QtWidgets.QLineEdit(self.mainFrame)
        self.buscar_edit.setGeometry(QtCore.QRect(80, 20, 251, 20))
        self.buscar_edit.setObjectName("buscar_edit")
        self.lbl_downloads = QtWidgets.QLabel(self.mainFrame)
        self.lbl_downloads.setGeometry(QtCore.QRect(370, 20, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_downloads.setFont(font)
        self.lbl_downloads.setStyleSheet("color: rgb(0, 0, 0);")
        self.lbl_downloads.setObjectName("lbl_downloads")
        self.tab_main.addTab(self.ds_tab, "")
        self.rep_tab = QtWidgets.QWidget()
        self.rep_tab.setObjectName("rep_tab")
        self.frame = QtWidgets.QFrame(self.rep_tab)
        self.frame.setGeometry(QtCore.QRect(90, 39, 521, 161))
        self.frame.setStyleSheet("\n"
"background-color: rgb(183, 131, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.tab_main.addTab(self.rep_tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 741, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tab_main.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Youtube Downloader"))
        self.button_play.setText(_translate("MainWindow", "Play"))
        self.button_anterior.setText(_translate("MainWindow", "Anterior"))
        self.button_proxima.setText(_translate("MainWindow", "Proxima"))
        self.button_parar.setText(_translate("MainWindow", "Parar"))
        self.button_pause.setText(_translate("MainWindow", "Pause"))
        self.lbl_bucar.setText(_translate("MainWindow", "Buscar:"))
        self.lbl_downloads.setText(_translate("MainWindow", "Downloads"))
        self.tab_main.setTabText(self.tab_main.indexOf(self.ds_tab), _translate("MainWindow", "D.S"))
        self.tab_main.setTabText(self.tab_main.indexOf(self.rep_tab), _translate("MainWindow", "Reprodução"))


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_MainWindow()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())